---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-installer"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-installer"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: "{{ .Release.Name }}-installer"
      volumes:
        - name: shared-data
          emptyDir: {}
        - name: certs
          emptyDir: {}
        - name: scripts
          configMap:
            name: "{{ .Release.Name }}-pre-install-scripts"
            defaultMode: 0555
      containers:
      - name: main
        image: "registry.access.redhat.com/openshift3/ose-cli:v3.11"
        command: [ "bash","-c","set -x; sleep 60 && /scripts/certutil.sh ca '{{ .Release.Name }}-ca' && /scripts/certutil.sh cert elasticsearch '--secret-name={{ .Release.Name }}-elasticsearch-cert' '--ca-secret-name={{ .Release.Name }}-ca'; /scripts/certutil.sh cred elasticsearch --secret-name={{ .Release.Name }}-elasticsearch-cred && /scripts/certutil.sh cert kibana '--secret-name={{ .Release.Name }}-kibana-cert' '--ca-secret-name={{ .Release.Name }}-ca' && /scripts/certutil.sh key '{{ .Release.Name }}-kibana-key' --size=50; touch /var/shared/done" ]
        env:
          - name: ESCT_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: shared-data
            mountPath: /var/shared
          - name: scripts
            mountPath: /scripts
      - name: oc
        image: "registry.access.redhat.com/openshift3/ose-cli:v3.11"
        command: ["bash","-c", "until [ -f /var/shared/done ]; do sleep 5; done"]
        volumeMounts:
          - name: shared-data
            mountPath: /var/shared
          - name: certs
            mountPath: /certs
      - name: certutil
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.7.0"
        command: ["bash","-c", "until [ -f /var/shared/done ]; do sleep 5; done"]
        volumeMounts:
          - name: shared-data
            mountPath: /var/shared
          - name: certs
            mountPath: /certs
      - name: openssl
        image: "frapsoft/openssl"
        command: ["sh","-c", "until [ -f /var/shared/done ]; do sleep 5; done"]
        volumeMounts:
          - name: shared-data
            mountPath: /var/shared
          - name: certs
            mountPath: /certs
